version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: exam-copilot-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: exam-copilot-db
      POSTGRES_USER: exam-copilot-user
      POSTGRES_PASSWORD: exam-copilot-password
    volumes:
      - postgresVolume:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: exam-copilot-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: mongo-password
    volumes:
      - mongoVolume:/data/db

volumes:
  postgresVolume:
  mongoVolume:
