version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: exam-copilot-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: exam-copilot-db
      POSTGRES_USER: exam-copilot-user
      POSTGRES_PASSWORD: exam-copilot-password
    volumes:
      - chatAgents:/var/lib/postgresql/data

volumes:
  chatAgents:
